// Code generated by wunderctl. DO NOT EDIT.

import type { ClientOperationErrors, GraphQLError } from "@wundergraph/sdk/client";

export type OperationErrors = {
	"WorkingLists/linkExam": WorkingListsLinkExamErrors;
	"WorkingLists/refreshLinkExam": WorkingListsRefreshLinkExamErrors;
	"users/get": UsersGetErrors;
	"users/subscribe": UsersSubscribeErrors;
	"users/update": UsersUpdateErrors;
};

export type WorkingListsLinkExamErrors = ClientOperationErrors;
export type WorkingListsRefreshLinkExamErrors = ClientOperationErrors;
export type UsersGetErrors = ClientOperationErrors;
export type UsersSubscribeErrors = ClientOperationErrors;
export type UsersUpdateErrors = ClientOperationErrors;
